mm_per_pixel: 1.0

zones:
  Room_1:
    type: room
    points:
      - [242, 19]
      - [234, 143]
      - [400, 147]
      - [390, 16]
    connections:
      - Tube_1
      - Tube_2
      - Tube_3

  Room_2:
    type: room
    points:
      - [5, 270]
      - [128, 266]
      - [126, 431]
      - [4, 437]
    connections:
      - Tube_1
      - Tube_3
      - Tube_4

  Room_3:
    type: room
    points:
      - [438, 589]
      - [443, 460]
      - [563, 461]
      - [554, 588]
    connections:
      - Tube_2
      - Tube_4

  Tube_1:
    type: tube
    points:
      - [237, 93]
      - [179, 103]
      - [134, 130]
      - [103, 177]
      - [80, 219]
      - [74, 264]

  Tube_2:
    type: tube
    points:
      - [400, 97]
      - [441, 112]
      - [469, 164]
      - [483, 215]
      - [490, 282]
      - [489, 372]
      - [492, 453]

  Tube_3:
    type: tube
    points:
      - [315, 147]
      - [313, 213]
      - [328, 254]
      - [369, 319]
      - [385, 382]
      - [358, 448]
      - [308, 494]
      - [227, 534]
      - [143, 526]
      - [95, 485]
      - [71, 438]

  Tube_4:
    type: tube
    points:
      - [133, 353]
      - [197, 359]
      - [239, 390]
      - [270, 429]
      - [306, 476]
      - [342, 510]
      - [410, 520]
      - [435, 518]
